### ISSUE TITLE
Backend - add routes in order for it to persist with the cart

### ISSUE THREAD

**Issue by MelindaL17** [indigo-iguanas/graceshopper#19]
user does not have to be logged in, in order for the cart to persist.

**Comment by zacharyad** [comment]
Routes will include:
post to "api/cart/:id" , placing items into cart with userId and status defaulting ton "inCart"
get route to "api/cart/:id", getting all orders with a status of "inCart" where the userId is matching.

**Comment by dhf-fullstack** [comment]
zacharayad's work is done; melinda's comment about persistent guest cart is address in #51
